apiVersion: v1
kind: Namespace
metadata:
  name: dfgdfgdfg-dev
  labels:
    environment-id: env_91cae54b-a17f-468c-854f-ec8a50f4e022
    project-id: project_d404651a-8af1-453a-9987-14b4696709aa
    project-name: dfgdfgdfg
    environment-name: dev
    organization-id: org_9aad87d0-abbc-48f9-9038-002316f0475a
